services:
  db:
    image: postgres:15
    # persist data beyond lifetime of container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=the_link
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 2s
      retries: 10
  # redis:
  #   image: redis
  #   # persistent storage
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis_data:/data
  #   healthcheck:
  #     test: bash -c 'exec 6<>/dev/tcp/redis/6379'
  #     interval: 2s
  #     retries: 10
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      # redis:
      #   condition: service_healthy
  # celery:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   command: celery -A the_link worker -l INFO --beat --pool=solo
  #   volumes:
  #     - .:/code
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy

volumes:
  postgres_data:
  # redis_data:
