# syntax = docker/dockerfile:1.5
FROM python:3.11
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set environment variables
ARG ENVIRONMENT
ENV ENVIRONMENT=$ENVIRONMENT
ARG SECRET_KEY
ENV SECRET_KEY=$SECRET_KEY
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ARG SIMPLE_JWT_SIGNING_KEY
ENV SIMPLE_JWT_SIGNING_KEY=$SIMPLE_JWT_SIGNING_KEY
ARG CORS_ALLOWED_ORIGINS
ENV CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS
ARG LEGACY_DB_PASSWORD
ENV LEGACY_DB_PASSWORD=$LEGACY_DB_PASSWORD
ARG LEGACY_DB_HOST
ENV LEGACY_DB_HOST=$LEGACY_DB_HOST
ARG AWS_REGION
ENV AWS_REGION=$AWS_REGION
ARG S3_BUCKET
ENV S3_BUCKET=$S3_BUCKET
ARG LAMBDA_FUNCTION_URL
ENV LAMBDA_FUNCTION_URL=$LAMBDA_FUNCTION_URL
ARG BACKEND_CALLBACK_URL
ENV BACKEND_CALLBACK_URL=$BACKEND_CALLBACK_URL
ARG FRONTEND_BASE_URL
ENV FRONTEND_BASE_URL=$FRONTEND_BASE_URL
ARG SENDGRID_API_KEY
ENV SENDGRID_API_KEY=$SENDGRID_API_KEY
ARG NOTICES_LAMBDA_FUNCTION_URL
ENV NOTICES_LAMBDA_FUNCTION_URL=$NOTICES_LAMBDA_FUNCTION_URL
ARG BACKEND_NOTICES_CALLBACK_URL
ENV BACKEND_NOTICES_CALLBACK_URL=$BACKEND_NOTICES_CALLBACK_URL
ARG PROCORE_CLIENT_ID
ENV PROCORE_CLIENT_ID=$PROCORE_CLIENT_ID
ARG PROCORE_CLIENT_SECRET
ENV PROCORE_CLIENT_SECRET=$PROCORE_CLIENT_SECRET
ARG PROCORE_REDIRECT_URL
ENV PROCORE_REDIRECT_URL=$PROCORE_REDIRECT_URL
ARG PROCORE_AUTH_BASE_URL
ENV PROCORE_AUTH_BASE_URL=$PROCORE_AUTH_BASE_URL
ARG PROCORE_BASE_URL
ENV PROCORE_BASE_URL=$PROCORE_BASE_URL

# install node/npm
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    echo "deb https://deb.nodesource.com/node_20.x bookworm main" > /etc/apt/sources.list.d/nodesource.list && \
    wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
    apt-get update && \
    apt-get install -yqq nodejs \
    # install gettext for translations
    gettext

# create code directory
RUN mkdir /code

# install python requirements
RUN pip install --upgrade pip

# copy just requirements and install before rest of code to avoid having to
# reinstall packages during build every time code changes
COPY requirements.txt requirements.txt
COPY requirements requirements/
RUN --mount=type=cache,target=/root/.cache \
    pip install -r requirements.txt

# copy code files
COPY . /code/
COPY docker-entrypoint.sh /code/
RUN chmod +x /code/docker-entrypoint.sh

WORKDIR /code

RUN adduser --disabled-password --gecos "" django
RUN chown -R django:django /code/

USER django
ENTRYPOINT ["./docker-entrypoint.sh"]
