# Generated by Django 5.1 on 2024-10-04 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0002_project_end_date_project_is_archived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterFormatSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('masterformat_number', models.CharField(max_length=256)),
                ('masterformat_description', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('masterformat_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.masterformatsection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmittalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paragraph_number', models.CharField(max_length=256)),
                ('submittal_type', models.CharField(max_length=256)),
                ('submittal_description', models.CharField(max_length=256)),
                ('submittal_content', models.TextField()),
                ('submittal_number', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('text_location', models.JSONField(blank=True, null=True)),
                ('additional_text_locations', models.JSONField(blank=True, null=True)),
                ('procore_submittal_id', models.CharField(blank=True, max_length=256, null=True)),
                ('procore_export_date', models.DateTimeField(blank=True, null=True)),
                ('parsing_method', models.CharField(max_length=256)),
                ('parsing_version', models.CharField(max_length=256)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_submittal_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.project')),
                ('spec_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.specsection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_submittal_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedSubmittalItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.project')),
                ('submittal_items', models.ManyToManyField(blank=True, to='deliverables.submittalitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_path', models.CharField(max_length=256)),
                ('parsed_document_path', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=256)),
                ('md5', models.CharField(max_length=256)),
                ('processing_status', models.CharField(max_length=256)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='submittalitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.uploadedfile'),
        ),
        migrations.AddField(
            model_name='specsection',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.uploadedfile'),
        ),
    ]
