# Generated by Django 5.1 on 2024-10-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0003_masterformatsection_specsection_submittalitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='procore_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='procore_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='procore_submittal_manager_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='procore_submittal_manager_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='submittalitem',
            name='legacy_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submittalitem',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submittalitem',
            name='legacy_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
