# Generated by Django 5.1 on 2024-10-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0006_alter_uploadedfile_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittalitem',
            name='legacy_created_at',
        ),
        migrations.AlterField(
            model_name='masterformatsection',
            name='masterformat_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='masterformatsection',
            name='masterformat_number',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
