# Generated by Django 5.1 on 2024-10-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0007_remove_submittalitem_legacy_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specsection',
            name='processing_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
