# Generated by Django 5.1 on 2024-10-08 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0010_alter_submittalitemlist_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittalitemlist',
            name='submittals',
            field=models.ManyToManyField(blank=True, related_name='submittal_lists', to='deliverables.submittalitem'),
        ),
        migrations.AddIndex(
            model_name='submittalitem',
            index=models.Index(fields=['spec_section'], name='deliverable_spec_se_3c3e56_idx'),
        ),
        migrations.AddIndex(
            model_name='submittalitem',
            index=models.Index(fields=['submittal_type'], name='deliverable_submitt_7e13b0_idx'),
        ),
        migrations.AddIndex(
            model_name='submittalitem',
            index=models.Index(fields=['submittal_description'], name='deliverable_submitt_ceb6cf_idx'),
        ),
    ]
