# Generated by Django 5.1 on 2024-10-08 18:48

from django.db import migrations, models


def convert_paragraph_number_to_heirarchical_number(paragraph_number):
        split_paragraph_number = paragraph_number.split('-')
        period_separated_parts = split_paragraph_number[0]
        if len(split_paragraph_number) > 1:
            appendage = split_paragraph_number[1]
        else:
            appendage = ""

        period_separated_parts = [part.zfill(5) for part in period_separated_parts.split('.')]
        heirarchical_period_part = '.'.join(period_separated_parts)
        if appendage:
            return heirarchical_period_part + '-' + appendage
        else:
            return heirarchical_period_part
    

class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0011_alter_submittalitemlist_submittals_and_more'),
    ]

    def backfill_heirarchical_paragraph_number(apps, schema_editor):
        SubmittalItem = apps.get_model('deliverables', 'SubmittalItem')
        for item in SubmittalItem.objects.all():
            item.heirarchical_paragraph_number = convert_paragraph_number_to_heirarchical_number(item.paragraph_number)
            item.save()

    operations = [
        migrations.AddField(
            model_name='submittalitem',
            name='heirarchical_paragraph_number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.RunPython(backfill_heirarchical_paragraph_number),
    ]
