# Generated by Django 5.1 on 2024-10-15 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0012_submittalitem_heirarchical_paragraph_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submittalitem',
            index=models.Index(fields=['project'], name='deliverable_project_f1229f_idx'),
        ),
    ]
