# Generated by Django 5.1 on 2024-10-17 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0013_submittalitem_deliverable_project_f1229f_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submittalitem',
            name='deliverable_spec_se_3c3e56_idx',
        ),
        migrations.RemoveField(
            model_name='submittalitem',
            name='spec_section',
        ),
        migrations.AddField(
            model_name='submittalitem',
            name='masterformat_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliverables.masterformatsection'),
        ),
        migrations.AlterField(
            model_name='submittalitem',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliverables.uploadedfile'),
        ),
        migrations.AddIndex(
            model_name='submittalitem',
            index=models.Index(fields=['masterformat_section'], name='deliverable_masterf_e2bb64_idx'),
        ),
    ]
