# Generated by Django 5.1 on 2024-10-17 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0014_remove_submittalitem_deliverable_spec_se_3c3e56_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittalitem',
            name='masterformat_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.masterformatsection'),
        ),
    ]
