# Generated by Django 5.1 on 2024-10-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0015_alter_submittalitem_masterformat_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='last_retry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
