# Generated by Django 5.1 on 2024-10-31 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0016_uploadedfile_last_retry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
