# Generated by Django 5.1 on 2024-11-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0017_remove_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
