# Generated by Django 5.1 on 2024-11-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0018_project_project_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
