# Generated by Django 5.1 on 2024-11-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0017_alter_project_status'),
        ('deliverables', '0019_project_project_type'),
    ]

    operations = [
    ]
