# Generated by Django 5.1 on 2024-11-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0020_merge_20241111_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=256),
        ),
    ]
