# Generated by Django 5.1 on 2024-11-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0020_excelexportheader'),
        ('deliverables', '0021_alter_project_status'),
    ]

    operations = [
    ]
