# Generated by Django 5.1 on 2024-11-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0022_merge_20241114_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
