# Generated by Django 5.1 on 2024-11-18 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliverables", "0023_remove_project_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeExcerpt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("anchor", models.CharField(max_length=256)),
                ("lines", models.JSONField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_excerpts",
                        to="deliverables.uploadedfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NoticeMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notice_type",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "notice_type_match",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("highlight_heuristic_match", models.TextField(blank=True, null=True)),
                ("highlight_discriminators", models.JSONField()),
                ("leading_anchor", models.CharField(max_length=256)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_matches",
                        to="deliverables.uploadedfile",
                    ),
                ),
                (
                    "excerpt_anchors",
                    models.ManyToManyField(
                        related_name="matches", to="deliverables.noticeexcerpt"
                    ),
                ),
                (
                    "masterformat_section",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliverables.masterformatsection",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_matches",
                        to="deliverables.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
