# Generated by Django 5.1 on 2024-12-14 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0024_noticeexcerpt_noticematch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcoreToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(max_length=1020)),
                ('refresh_token', models.CharField(max_length=1020)),
                ('expires_in', models.IntegerField()),
                ('token_type', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=1020)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procore_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
