# Generated by Django 5.1 on 2024-12-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0024_noticeexcerpt_noticematch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedSubmittalItemList',
        ),
    ]
