# Generated by Django 5.1 on 2024-12-23 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0025_procoretoken'),
        ('teams', '0007_delete_teamprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcoreSubmittalTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procore_company_id', models.CharField(max_length=256)),
                ('link_type', models.CharField(max_length=256)),
                ('procore_type', models.CharField(max_length=256)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'unique_together': {('company', 'link_type')},
            },
        ),
    ]
