# Generated by Django 5.1 on 2024-12-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0026_procoresubmittaltypemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='procoretoken',
            name='redirect_uri',
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
    ]
