# Generated by Django 5.1 on 2024-12-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0025_delete_savedsubmittalitemlist'),
        ('deliverables', '0027_procoretoken_redirect_uri'),
    ]

    operations = [
    ]
