# Generated by Django 5.1 on 2025-01-02 04:35

from django.db import migrations


def populate_hierarchical_numbers(apps, schema_editor):
    SubmittalItem = apps.get_model('deliverables', 'SubmittalItem')
    
    for item in SubmittalItem.objects.all():
        split_paragraph_number = item.paragraph_number.split('-')
        period_separated_parts = split_paragraph_number[0]
        if len(split_paragraph_number) > 1:
            appendage = split_paragraph_number[1]
        else:
            appendage = ""

        period_separated_parts = [part.zfill(5) for part in period_separated_parts.split('.')]
        heirarchical_period_part = '.'.join(period_separated_parts)
        if appendage:
            heirarchical_paragraph_number = heirarchical_period_part + '-' + appendage.zfill(5)
        else:
            heirarchical_paragraph_number = heirarchical_period_part
        item.heirarchical_paragraph_number = heirarchical_paragraph_number
        item.save()

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0028_merge_20241231_2205'),
    ]

    operations = [
        migrations.RunPython(populate_hierarchical_numbers, reverse_migration),
    ]
