# Generated by Django 5.1 on 2025-01-09 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0029_populate_hierarchical_paragraph_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='specsection',
            name='processing_method',
            field=models.CharField(blank=True, choices=[('REGEX_UNABLE_TO_DETECT_SUBMITTALS', 'Regex Unable to Detect Submittals'), ('REGEX_SUCCESS', 'Regex Success')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='submittalitem',
            name='spec_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deliverables.specsection'),
        ),
        migrations.AlterField(
            model_name='submittalitem',
            name='masterformat_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliverables.masterformatsection'),
        ),
    ]
