# Generated by Django 5.1 on 2025-01-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0030_specsection_processing_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittalitem',
            name='added_under_submittal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliverables.submittalitem'),
        ),
        migrations.AddField(
            model_name='submittalitem',
            name='manually_added',
            field=models.BooleanField(default=False),
        ),
    ]
