# Generated by Django 5.1 on 2025-01-24 14:57

from django.db import migrations

def create_default_versions(apps, schema_editor):
    Project = apps.get_model('deliverables', 'Project')
    ProjectVersion = apps.get_model('deliverables', 'ProjectVersion')
    UploadedFile = apps.get_model('deliverables', 'UploadedFile')
    SubmittalItem = apps.get_model('deliverables', 'SubmittalItem')
    SubmittalItemList = apps.get_model('deliverables', 'SubmittalItemList')
    NoticeMatch = apps.get_model('deliverables', 'NoticeMatch')

    project_to_version_map = {}
    # Create a default version for each project that doesn't have one
    projects = Project.objects.all()
    print(f"Creating default versions for {len(projects)} projects")
    for project in projects:
        # Check if project already has any versions to avoid duplicates
        if not ProjectVersion.objects.filter(project=project).exists():
            project_version = ProjectVersion.objects.create(
                project=project,
                version_name=f"{project.name} - Version 1",
                version_number=1,
                created_by=None
            )
            print(f"Created default version: {project_version} for project {project.name}")
            project_to_version_map[project.id] = project_version
    print("\nCreated default versions for all projects")

    for project_id, project_version in project_to_version_map.items():
        UploadedFile.objects.filter(project_id=project_id).update(project_version=project_version)
    print("Associated uploaded files with default versions")

    for project_id, project_version in project_to_version_map.items():
        SubmittalItem.objects.filter(project_id=project_id).update(project_version=project_version)
    print("Associated submittal items with default versions")

    for project_id, project_version in project_to_version_map.items():
        SubmittalItemList.objects.filter(project_id=project_id).update(project_version=project_version)
    print("Associated submittal item lists with default versions")

    for project_id, project_version in project_to_version_map.items():
        NoticeMatch.objects.filter(project_id=project_id).update(project_version=project_version)
    print("Associated notice matches with default versions")



def reverse_default_versions(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0032_projectversion_noticematch_project_version_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_versions, reverse_default_versions),
    ]
