# Generated by Django 5.1 on 2025-01-24 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0033_create_default_project_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticematch',
            name='project_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.projectversion'),
        ),
        migrations.AlterField(
            model_name='submittalitem',
            name='project_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.projectversion'),
        ),
        migrations.AlterField(
            model_name='submittalitemlist',
            name='project_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.projectversion'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='project_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.projectversion'),
        ),
    ]
