# Generated by Django 5.1 on 2025-01-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0034_alter_noticematch_project_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectversion',
            name='version_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
