# Generated by Django 5.1 on 2025-01-29 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0035_alter_projectversion_version_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_versions', to=settings.AUTH_USER_MODEL),
        ),
    ]
