# Generated by Django 5.1 on 2025-01-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0036_projectversion_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectversion',
            options={'ordering': ['created_at']},
        ),
    ]
