# Generated by Django 5.1 on 2025-01-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0037_alter_projectversion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
