# Generated by Django 5.1 on 2025-01-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0038_projectversion_is_archived'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectversion',
            name='unique_project_version_name',
        ),
    ]
