# Generated by Django 5.1 on 2025-01-31 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0039_remove_projectversion_unique_project_version_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectversion',
            constraint=models.UniqueConstraint(fields=('project', 'version_name'), name='unique_project_version_name'),
        ),
    ]
