# Generated by Django 5.1 on 2025-02-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0040_projectversion_unique_project_version_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='processing_method',
            field=models.CharField(choices=[('V1', 'V1'), ('V2', 'V2')], default='V1', max_length=256),
        ),
    ]
