# Generated by Django 5.1 on 2025-02-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0041_uploadedfile_processing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='specsection',
            name='file_s3_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
