# Generated by Django 5.1 on 2025-04-11 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0042_specsection_file_s3_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittalitem',
            name='added_under_submittal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliverables.submittalitem'),
        ),
        migrations.AlterField(
            model_name='submittalitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_submittal_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submittalitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_submittal_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
