# Generated by Django 5.1 on 2025-04-16 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0043_alter_submittalitem_added_under_submittal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='processing_method',
            field=models.CharField(choices=[('V1', 'V1'), ('V2', 'V2'), ('FULL_SPEC_PROCESSING', 'Full Spec Processing')], default='V1', max_length=256),
        ),
        migrations.CreateModel(
            name='SemanticallyProcessedSpecItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paragraph_number', models.CharField(max_length=256)),
                ('heirarchical_paragraph_number', models.CharField(blank=True, default='', max_length=256)),
                ('text_location', models.JSONField(blank=True, null=True)),
                ('additional_text_locations', models.JSONField(blank=True, null=True)),
                ('parsing_method', models.CharField(max_length=256)),
                ('parsing_version', models.CharField(max_length=256)),
                ('spec_section_part', models.CharField(max_length=256)),
                ('topic', models.CharField(max_length=256)),
                ('item_type', models.CharField(max_length=256)),
                ('item_content', models.TextField()),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliverables.uploadedfile')),
                ('masterformat_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliverables.masterformatsection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.project')),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.projectversion')),
                ('spec_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deliverables.specsection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
