# Generated by Django 5.1 on 2025-04-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0044_alter_uploadedfile_processing_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanticallyprocessedspecitem',
            name='item_type',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='semanticallyprocessedspecitem',
            name='topic',
            field=models.JSONField(),
        ),
    ]
