# Generated by Django 5.1 on 2025-05-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0045_alter_semanticallyprocessedspecitem_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='specgpt_embedding_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='specgpt_processing_status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading'), ('IN_QUEUE', 'In Queue'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('NONE', 'None')], default='NONE', max_length=256),
        ),
    ]
