# Generated by Django 5.1 on 2025-05-23 02:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0046_uploadedfile_specgpt_embedding_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specsection',
            name='specgpt_embedding_status',
            field=models.CharField(blank=True, choices=[('UPLOADING', 'Uploading'), ('IN_QUEUE', 'In Queue'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('NONE', 'None')], max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.project')),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.projectversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history', models.JSONField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.chat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
