# Generated by Django 5.1 on 2025-05-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0047_specsection_specgpt_embedding_status_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ai_message_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sources',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
