# Generated by Django 5.1 on 2025-05-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0048_chatmessage_ai_message_id_chatmessage_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='ai_message_id',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='history',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(choices=[('ai', 'ai'), ('human', 'human')], default='ai', max_length=256),
            preserve_default=False,
        ),
    ]
