# Generated by Django 5.1 on 2025-05-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0049_remove_chatmessage_ai_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='raw_message',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
