# Generated by Django 5.1 on 2025-06-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0051_alter_chatmessage_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specsection',
            name='specgpt_embedding_status',
            field=models.CharField(blank=True, choices=[('UPLOADING', 'Uploading'), ('IN_QUEUE', 'In Queue'), ('SUBSECTIONS_EXTRACTED', 'Subsections Extracted'), ('SECTION_PROCESSING_FAILED', 'Section Processing Failed'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('NONE', 'None')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='specgpt_processing_status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading'), ('IN_QUEUE', 'In Queue'), ('SUBSECTIONS_EXTRACTED', 'Subsections Extracted'), ('SECTION_PROCESSING_FAILED', 'Section Processing Failed'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('NONE', 'None')], default='NONE', max_length=256),
        ),
    ]
