# Generated by Django 5.1 on 2025-07-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0052_alter_specsection_specgpt_embedding_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(choices=[('ai', 'ai'), ('human', 'human'), ('system', 'system'), ('error', 'error'), ('ai_inspection_log', 'ai_inspection_log')], max_length=256),
        ),
    ]
