# Generated by Django 5.1 on 2025-07-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0053_alter_chatmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(choices=[('ai', 'ai'), ('human', 'human'), ('system', 'system'), ('error', 'error'), ('ai_inspection_log', 'ai_inspection_log'), ('ai_owner_deliverables_log', 'ai_owner_deliverables_log')], max_length=256),
        ),
    ]
