# Generated by Django 5.1 on 2025-07-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0054_alter_chatmessage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='specsection',
            name='custom_section_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
