# Generated by Django 5.1 on 2025-08-15 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0055_specsection_custom_section_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiGeneratedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_type', models.CharField(max_length=256)),
                ('log_status', models.CharField(max_length=256)),
                ('log_table', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.project')),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.projectversion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
