# Generated by Django 5.1 on 2025-08-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0056_add_aigeneratedlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigeneratedlog',
            name='log_table',
            field=models.TextField(blank=True, null=True),
        ),
    ]
