# Generated by Django 5.1 on 2025-08-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0057_alter_aigeneratedlog_log_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedlog',
            name='log_data',
            field=models.JSONField(blank=True, help_text='Structured data for inspection logs and owner deliverables logs', null=True),
        ),
    ]
