# Generated by Django 5.1 on 2025-09-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0058_aigeneratedlog_log_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedlog',
            name='completion_status',
            field=models.JSONField(blank=True, help_text='Status of each QA option processing', null=True),
        ),
        migrations.AddField(
            model_name='aigeneratedlog',
            name='qa_options_selected',
            field=models.JSONField(blank=True, help_text='Selected QA options for qa_planner log type', null=True),
        ),
    ]
