# Generated by Django 5.1 on 2025-10-14 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0059_add_qa_planner_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('color', models.CharField(help_text='Highlight color in HEX (e.g., #FFDD00)', max_length=7)),
                ('quads', models.JSONField(blank=True, default=list, help_text='Array of text quads for highlight annotation (each quad = [x1,y1,x2,y2,x3,y3,x4,y4])')),
                ('xfdf_data', models.TextField(help_text='Full XFDF string for this annotation. It will be used for import/exporting-ing the annotations')),
                ('tag', models.CharField(blank=True, help_text='Optional label or tag for categorizing annotations', max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_annotations', to='deliverables.project')),
                ('spec_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_annotations', to='deliverables.specsection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_pdf_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
