# Generated by Django 5.1 on 2025-10-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0060_pdfannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfannotation',
            name='project_version',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='deliverables.projectversion'),
            preserve_default=False,
        ),
    ]
