# Generated by Django 5.1 on 2025-10-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0061_pdfannotation_project_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfannotation',
            name='id',
            field=models.IntegerField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
