# Generated by Django 5.1 on 2025-10-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0062_alter_pdfannotation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfannotation',
            name='annotation_id',
            field=models.CharField(blank=True, help_text='Frontend-generated annotation ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfannotation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
