# Generated by Django 5.1 on 2025-10-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0063_pdfannotation_annotation_id_alter_pdfannotation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfannotation',
            name='annotation_id',
            field=models.CharField(help_text='Frontend-generated annotation ID', max_length=255, unique=True),
        ),
    ]
