# Generated by Django 5.1 on 2025-11-06 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0064_alter_pdfannotation_annotation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedlog',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered this AI log generation (null for system-generated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generated_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('AI', 'AI Generated'), ('HUMAN', 'Human Created')], default='AI', help_text='Whether this was AI-generated or human-created', max_length=10)),
                ('spec_section_number', models.CharField(max_length=256)),
                ('spec_section_name', models.CharField(max_length=512)),
                ('paragraph_number', models.CharField(blank=True, max_length=256, null=True)),
                ('extraction_type', models.CharField(help_text='For AI: log type (inspection_log, owner_deliverables_log, qa_planner). For HUMAN: user-selected base type', max_length=256)),
                ('item_type', models.CharField(blank=True, help_text='Specific categorization - for QA planner subtypes or user-selected type for highlights', max_length=256, null=True)),
                ('requirement_text', models.TextField()),
                ('responsible_party', models.CharField(blank=True, max_length=512, null=True)),
                ('when_due', models.CharField(blank=True, max_length=512, null=True)),
                ('inspection_frequency', models.CharField(blank=True, max_length=256, null=True)),
                ('deliverable_type', models.CharField(blank=True, max_length=256, null=True)),
                ('pdf_locations', models.JSONField(blank=True, help_text='PDF coordinate data for highlighting', null=True)),
                ('ai_generated_log', models.ForeignKey(blank=True, help_text='AI log this was extracted from (null for human-created)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracted_items', to='deliverables.aigeneratedlog')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this extraction (for HUMAN source) or triggered AI generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_extractions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.project')),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverables.projectversion')),
                ('spec_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliverables.specsection')),
            ],
            options={
                'db_table': 'deliverables_extracted_data',
                'ordering': ['spec_section_number', 'id'],
                'indexes': [models.Index(fields=['project', 'project_version'], name='deliverable_project_0c0db9_idx'), models.Index(fields=['spec_section_number'], name='deliverable_spec_se_3ff65a_idx'), models.Index(fields=['extraction_type', 'item_type'], name='deliverable_extract_a76b38_idx'), models.Index(fields=['source'], name='deliverable_source_3f8caa_idx'), models.Index(fields=['created_by'], name='deliverable_created_6ec4e0_idx')],
            },
        ),
    ]
