# Generated by Django 5.1 on 2025-11-06 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0064_alter_pdfannotation_annotation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanticallyprocessedspecitem',
            name='spec_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliverables.specsection'),
        ),
        migrations.AlterField(
            model_name='submittalitem',
            name='spec_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliverables.specsection'),
        ),
    ]
