# Generated by Django 5.1 on 2025-11-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0065_aigeneratedlog_created_by_extracteddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracteddata',
            name='deliverable_type',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='inspection_frequency',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='when_due',
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Type-specific data: inspection_frequency, when_due, deliverable_type, etc.', null=True),
        ),
    ]
