# Generated by Django 5.1 on 2025-11-06 04:30

from django.db import migrations, transaction
import logging

logger = logging.getLogger(__name__)

def migrate_ai_log_data(apps, schema_editor):
    """Migrate data from AiGeneratedLog.log_data to ExtractedData model"""
    AiGeneratedLog = apps.get_model('deliverables', 'AiGeneratedLog')
    ExtractedData = apps.get_model('deliverables', 'ExtractedData')

    text_field_map = {
        'inspection_log': 'Inspection Type And Requirements',
        'owner_deliverables_log': 'Exact Requirement Text',
        'qa_planner': 'Requirement Text',
    }

    # Process each AI log
    for ai_log in AiGeneratedLog.objects.filter(log_status='SUCCESS').iterator(chunk_size=100):
        if not ai_log.log_data:
            continue

        extracted_items = []

        try:
            with transaction.atomic():
                for item in ai_log.log_data:
                    text_field = text_field_map.get(ai_log.log_type)

                    extracted_data = {
                        'ai_generated_log': ai_log,
                        'project': ai_log.project,
                        'project_version': ai_log.project_version,
                        'extraction_type': ai_log.log_type,
                        'source': 'AI',
                        'metadata': {},
                    }

                    if hasattr(ai_log, 'created_by'):
                        extracted_data['created_by'] = ai_log.created_by

                    extracted_data['spec_section_number'] = item.get('Spec Section #', '')
                    extracted_data['spec_section_name'] = item.get('Spec Section Name', '')
                    extracted_data['responsible_party'] = item.get('Responsible Party')
                    extracted_data['pdf_locations'] = item.get('pdf_locations')

                    if text_field:
                        extracted_data['requirement_text'] = item.get(text_field, '')
                        extracted_data['metadata']['original_text_key'] = text_field
                    else:
                        extracted_data['requirement_text'] = str(item)
                        extracted_data['metadata']['original_text_key'] = None

                    if ai_log.log_type == 'inspection_log':
                        extracted_data['metadata'].update({
                            'inspection_frequency': item.get('Inspection Frequency'),
                            'when_due': item.get('Inspection Frequency'),
                        })

                    elif ai_log.log_type == 'owner_deliverables_log':
                        extracted_data['metadata'].update({
                            'deliverable_type': item.get('Deliverable Type'),
                            'when_due': item.get('When Due'),
                        })

                    elif ai_log.log_type == 'qa_planner':
                        extracted_data['item_type'] = item.get('item_type')
                        extracted_data['paragraph_number'] = item.get('Paragraph Number')
                        extracted_data['metadata'].update({
                            'when_due': item.get('When Due'),
                        })

                    extracted_data['metadata']['raw_item'] = item

                    extracted_items.append(ExtractedData(**extracted_data))

                # Bulk create for efficiency
                if extracted_items:
                    ExtractedData.objects.bulk_create(extracted_items, batch_size=100)
                    logger.info(f"Migrated {len(extracted_items)} items from AiGeneratedLog {ai_log.id}")

        except Exception as e:
            logger.error(f"Error migrating AiGeneratedLog {ai_log.id}: {e}")
            continue

    total_count = ExtractedData.objects.count()
    logger.info(f"Migration complete. Total ExtractedData records: {total_count}")

def reverse_migration(apps, schema_editor):
    """Reverse the migration by deleting ExtractedData records"""
    ExtractedData = apps.get_model('deliverables', 'ExtractedData')
    count = ExtractedData.objects.count()
    ExtractedData.objects.all().delete()
    logger.info(f"Deleted {count} ExtractedData records")

class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0066_remove_extracteddata_deliverable_type_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_ai_log_data,
            reverse_migration,
            elidable=False
        ),
    ]
