# Generated by Django 5.1 on 2025-11-06 16:31

from django.db import migrations
import logging
import re

logger = logging.getLogger(__name__)


def fuzzy_match_spec_section(spec_section_number, spec_sections_cache):
    """
    Find SpecSection by fuzzy matching spec_section_number to masterformat_number.
    Returns the matching SpecSection or None.
    """
    if not spec_section_number:
        return None

    # Normalize the input spec section number (remove all non-digits)
    normalized_input = re.sub(r'[^\d]', '', str(spec_section_number))
    if not normalized_input:
        return None

    # Find matching spec section by comparing normalized numbers
    for spec_section_id, normalized_masterformat in spec_sections_cache.items():
        if normalized_input == normalized_masterformat:
            return spec_section_id

    return None


def backfill_spec_section(apps, schema_editor):
    """Backfill spec_section FK for all ExtractedData records"""
    ExtractedData = apps.get_model('deliverables', 'ExtractedData')
    SpecSection = apps.get_model('deliverables', 'SpecSection')

    # Get all extracted data records that need backfilling
    extracted_items = ExtractedData.objects.filter(spec_section__isnull=True).select_related('project', 'project_version')

    total_count = extracted_items.count()
    logger.info(f"Starting backfill of spec_section for {total_count} ExtractedData records")

    if total_count == 0:
        logger.info("No records to backfill")
        return

    # Process by project to optimize queries
    projects = set()
    for item in extracted_items.iterator(chunk_size=100):
        projects.add((item.project_id, item.project_version_id))

    updated_count = 0
    not_found_count = 0

    for project_id, project_version_id in projects:
        # Build cache of spec sections for this project
        spec_sections_query = SpecSection.objects.filter(
            document__project_id=project_id
        ).select_related('masterformat_section')

        if project_version_id:
            spec_sections_query = spec_sections_query.filter(
                document__project_version_id=project_version_id
            )

        # Cache: spec_section_id -> normalized_masterformat_number
        spec_sections_cache = {}
        for spec_section in spec_sections_query:
            if spec_section.masterformat_section:
                masterformat_number = spec_section.masterformat_section.masterformat_number
                normalized = re.sub(r'[^\d]', '', str(masterformat_number))
                spec_sections_cache[spec_section.id] = normalized

        # Get extracted items for this project
        project_items = ExtractedData.objects.filter(
            project_id=project_id,
            spec_section__isnull=True
        )

        if project_version_id:
            project_items = project_items.filter(project_version_id=project_version_id)

        # Update each item
        for item in project_items:
            spec_section_id = fuzzy_match_spec_section(
                item.spec_section_number,
                spec_sections_cache
            )

            if spec_section_id:
                item.spec_section_id = spec_section_id
                item.save(update_fields=['spec_section'])
                updated_count += 1
            else:
                not_found_count += 1
                logger.warning(
                    f"Could not find SpecSection for ExtractedData {item.id} "
                    f"with spec_section_number='{item.spec_section_number}'"
                )

    logger.info(
        f"Backfill complete: {updated_count} updated, {not_found_count} not found"
    )


def reverse_backfill(apps, schema_editor):
    """Reverse the backfill by clearing spec_section FK"""
    ExtractedData = apps.get_model('deliverables', 'ExtractedData')
    count = ExtractedData.objects.filter(spec_section__isnull=False).update(spec_section=None)
    logger.info(f"Reversed backfill: cleared spec_section for {count} records")


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0067_migrate_ai_log_data_to_extracted'),
    ]

    operations = [
        migrations.RunPython(
            backfill_spec_section,
            reverse_backfill,
            elidable=False
        ),
    ]
