# Generated by Django 5.1 on 2025-11-11 00:00

import django.db.models.deletion
from django.conf import settings
from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0065_alter_semanticallyprocessedspecitem_spec_section_and_more'),
        ('deliverables', '0068_backfill_extracted_data_spec_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Readable label (e.g. 'Safety Requirements').", max_length=100)),
                ('color', models.CharField(
                    default='#3B82F6',
                    help_text='HEX code used by the frontend for highlight color.',
                    max_length=7,
                    validators=[RegexValidator(regex='^#[0-9A-Fa-f]{6}$', message='Color must be in HEX format (#RRGGBB).')],
                )),
                ('description', models.TextField(blank=True, default='', help_text='Optional explanation of how this tag should be used.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag so we can hide a type without losing history.')),
                ('created_by', models.ForeignKey(
                    help_text='User who defined this custom type.',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_custom_item_types',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('project', models.ForeignKey(
                    help_text='Owning project.',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='custom_item_types',
                    to='deliverables.project',
                )),
            ],
            options={
                'db_table': 'deliverables_custom_item_type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='custom_item_type',
            field=models.ForeignKey(
                blank=True,
                help_text='User-defined grouping (only valid for custom highlights)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='extracted_data_items',
                to='deliverables.customitemtype',
            ),
        ),
        migrations.AddIndex(
            model_name='customitemtype',
            index=models.Index(fields=['project', 'is_active'], name='deliverable_project_ded537_idx'),
        ),
        migrations.AddIndex(
            model_name='customitemtype',
            index=models.Index(fields=['created_by'], name='deliverable_created_96b068_idx'),
        ),
        migrations.AddConstraint(
            model_name='customitemtype',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_custom_item_type_per_project'),
        ),
    ]

