# Generated by Django 5.1 on 2025-11-19 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0069_custom_item_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='Note content')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_notes', to=settings.AUTH_USER_MODEL)),
                ('extracted_data', models.ForeignKey(help_text='The highlight this note is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='deliverables.extracteddata')),
            ],
            options={
                'db_table': 'deliverables_extraction_note',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['extracted_data', 'created_at'], name='deliverable_extract_048649_idx'), models.Index(fields=['created_by'], name='deliverable_created_e27089_idx')],
            },
        ),
    ]
