# Generated by Django 5.1 on 2025-11-19 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0069_custom_item_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHighlightPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_custom_type', models.BooleanField(default=False, help_text='True if last highlight was a custom type, False if standard type.')),
                ('standard_item_type', models.CharField(blank=True, default='', help_text="Standard type name (e.g., 'inspections', 'warranties') if is_custom_type=False.", max_length=100)),
                ('extraction_type', models.CharField(blank=True, default='', help_text="The extraction_type used (e.g., 'qa_planner', 'custom_highlights').", max_length=100)),
                ('type_display_name', models.CharField(help_text="Human-readable name to display (e.g., 'Inspections', 'Safety Requirements').", max_length=200)),
                ('type_color', models.CharField(help_text='HEX color code for visual display.', max_length=7)),
                ('custom_item_type', models.ForeignKey(blank=True, help_text='Reference to custom type if is_custom_type=True.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_preferences', to='deliverables.customitemtype')),
                ('project', models.ForeignKey(help_text='Project context for this preference.', on_delete=django.db.models.deletion.CASCADE, related_name='user_highlight_preferences', to='deliverables.project')),
                ('user', models.ForeignKey(help_text='User who owns this preference.', on_delete=django.db.models.deletion.CASCADE, related_name='highlight_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deliverables_user_highlight_preference',
                'indexes': [models.Index(fields=['user', 'project'], name='deliverable_user_id_563506_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'project'), name='unique_highlight_preference_per_user_project')],
            },
        ),
    ]
