# Generated by Django 5.1 on 2025-12-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0070_add_extraction_note'),
        ('deliverables', '0070_userhighlightpreference'),
    ]

    operations = [
    ]
