# Generated by Django 5.1 on 2025-11-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0070_add_extraction_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanticallyprocessedspecitem',
            name='paragraph_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='submittalitem',
            name='paragraph_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
