# Generated by Django 5.1 on 2025-12-28 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0071_merge_20251212_1646'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingNoteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header', models.CharField(max_length=512)),
                ('header_bbox', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DrawingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=512)),
                ('file_s3_key', models.CharField(max_length=1024)),
                ('md5', models.CharField(max_length=64)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_files', to='deliverables.project')),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_files', to='deliverables.projectversion')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_drawing_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=128, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('output_s3_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('failure_summary', models.CharField(blank=True, max_length=256, null=True)),
                ('drawing_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='deliverables.drawingfile')),
            ],
        ),
        migrations.CreateModel(
            name='DrawingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_number', models.IntegerField()),
                ('category', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('source_blocks', models.JSONField(blank=True, null=True)),
                ('drawing_references', models.JSONField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='deliverables.drawingnotesection')),
            ],
            options={
                'ordering': ['note_number'],
            },
        ),
        migrations.CreateModel(
            name='DrawingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.IntegerField()),
                ('page_type', models.CharField(choices=[('drawing', 'Drawing'), ('spec', 'Specification')], max_length=32)),
                ('extraction_status', models.CharField(choices=[('success', 'Success'), ('no_notes_found', 'No Notes Found'), ('failed', 'Failed')], max_length=32)),
                ('spec_content', models.TextField(blank=True, null=True)),
                ('drawing_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='deliverables.drawingfile')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='deliverables.drawingextraction')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.AddField(
            model_name='drawingnotesection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_sections', to='deliverables.drawingpage'),
        ),
        migrations.CreateModel(
            name='DrawingExtractionWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('new_status', models.CharField(max_length=32)),
                ('output_s3_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='deliverables.drawingextraction')),
            ],
            options={
                'indexes': [models.Index(fields=['extraction', 'new_status'], name='deliverable_extract_9e8136_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='drawingfile',
            index=models.Index(fields=['project', 'project_version'], name='deliverable_project_316a36_idx'),
        ),
        migrations.AddIndex(
            model_name='drawingextraction',
            index=models.Index(fields=['drawing_file', 'status'], name='deliverable_drawing_30bfad_idx'),
        ),
        migrations.AddIndex(
            model_name='drawingnote',
            index=models.Index(fields=['category'], name='deliverable_categor_ef92f2_idx'),
        ),
    ]
