# Generated by Django 5.1 on 2026-01-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0072_add_drawing_parser_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingnote',
            name='raw_bounding_box',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingnote',
            name='rotated_bounding_box',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingnote',
            name='unrotated_bounding_box',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingnotesection',
            name='rotated_header_bbox',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingnotesection',
            name='unrotated_header_bbox',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingpage',
            name='rotated_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingpage',
            name='rotated_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingpage',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drawingpage',
            name='unrotated_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingpage',
            name='unrotated_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
