# Generated by Django 5.1 on 2026-01-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0073_drawingnote_raw_bounding_box_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specsection',
            options={'ordering': ['masterformat_section__masterformat_number', 'document__name']},
        ),
    ]
