# Generated by Django 5.1 on 2026-01-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0074_alter_specsection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingpage',
            name='sheet_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='drawingpage',
            name='sheet_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
