# Generated by Django 5.1 on 2026-01-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0075_add_sheet_number_and_title_to_drawing_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingpage',
            name='sheet_number',
            field=models.CharField(blank=True, db_index=True, help_text="The sheet number from the drawing title block (e.g., 'A-101', 'M-203')", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='drawingpage',
            name='sheet_title',
            field=models.CharField(blank=True, db_index=True, help_text="The sheet title from the drawing title block (e.g., 'FLOOR PLAN - DRAINAGE - MAIN')", max_length=512, null=True),
        ),
    ]
