# Generated by Django 5.1 on 2026-02-03 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0076_add_indexes_to_sheet_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes_processed', models.IntegerField(default=0)),
                ('notes_skipped', models.IntegerField(default=0)),
                ('spec_files_processed', models.IntegerField(default=0)),
                ('notes_with_mismatch', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('payload_s3_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_comparisons', to='deliverables.project')),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_comparisons', to='deliverables.projectversion')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_spec_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkippedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_id_from_lambda', models.CharField(max_length=64)),
                ('disciplines', models.JSONField(default=list)),
                ('sheet_discipline', models.CharField(blank=True, max_length=32, null=True)),
                ('reason', models.CharField(choices=[('unknown_discipline', 'Unknown Discipline'), ('skip_by_policy', 'Skip by Policy'), ('no_matching_specs', 'No Matching Specs'), ('malformed_discipline', 'Malformed Discipline')], max_length=32)),
                ('detail', models.TextField(blank=True, null=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skipped_in_comparisons', to='deliverables.drawingnote')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped_notes', to='deliverables.speccomparison')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SpecComparisonWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILED', 'Failed')], max_length=32)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='deliverables.speccomparison')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_id_from_lambda', models.CharField(max_length=64)),
                ('note_text', models.TextField()),
                ('spec_text', models.TextField()),
                ('spec_file_s3_key', models.CharField(max_length=1024)),
                ('spec_page_number', models.IntegerField()),
                ('spec_masterformat_number', models.CharField(max_length=256)),
                ('confidence', models.FloatField()),
                ('reason', models.TextField()),
                ('pdf_locations', models.JSONField(default=list)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='deliverables.speccomparison')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_conflicts', to='deliverables.drawingnote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='speccomparison',
            index=models.Index(fields=['project', 'project_version', 'created_at'], name='deliverable_project_6093d0_idx'),
        ),
        migrations.AddIndex(
            model_name='speccomparison',
            index=models.Index(fields=['project', 'status', 'completed_at'], name='deliverable_project_fb1acc_idx'),
        ),
        migrations.AddIndex(
            model_name='skippednote',
            index=models.Index(fields=['comparison', 'reason'], name='deliverable_compari_350281_idx'),
        ),
        migrations.AddIndex(
            model_name='specconflict',
            index=models.Index(fields=['comparison'], name='deliverable_compari_87273b_idx'),
        ),
    ]
