# Generated by Django 5.1 on 2026-01-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0076_add_indexes_to_sheet_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingpage',
            name='sheet_discipline',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('hazardous_materials', 'Hazardous Materials'), ('survey_mapping', 'Survey/Mapping'), ('geotechnical', 'Geotechnical'), ('civil', 'Civil'), ('landscape', 'Landscape'), ('structural', 'Structural'), ('architectural', 'Architectural'), ('interiors', 'Interiors'), ('equipment', 'Equipment'), ('fire_protection', 'Fire Protection'), ('plumbing', 'Plumbing'), ('process', 'Process'), ('mechanical', 'Mechanical'), ('electrical', 'Electrical'), ('distributed_energy', 'Distributed Energy'), ('telecommunications', 'Telecommunications'), ('resource', 'Resource'), ('other', 'Other'), ('contractor_shop', 'Contractor/Shop'), ('operations', 'Operations')], help_text='Primary discipline of the sheet based on sheet number prefix (e.g., M-101 → mechanical)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='drawingpage',
            name='sheet_discipline_confidence',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Confidence level of the discipline classification', max_length=16, null=True),
        ),
    ]
