# Generated by Django 5.1 on 2026-01-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0071_alter_semanticallyprocessedspecitem_paragraph_number_and_more'),
        ('deliverables', '0076_add_indexes_to_sheet_fields'),
    ]

    operations = [
    ]
