# Generated by Django 5.1 on 2026-01-30 02:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0077_add_discipline_fields_to_drawing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingnote',
            name='discipline_confidence',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Confidence level of the discipline classification', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='drawingnote',
            name='disciplines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('general', 'General'), ('hazardous_materials', 'Hazardous Materials'), ('survey_mapping', 'Survey/Mapping'), ('geotechnical', 'Geotechnical'), ('civil', 'Civil'), ('landscape', 'Landscape'), ('structural', 'Structural'), ('architectural', 'Architectural'), ('interiors', 'Interiors'), ('equipment', 'Equipment'), ('fire_protection', 'Fire Protection'), ('plumbing', 'Plumbing'), ('process', 'Process'), ('mechanical', 'Mechanical'), ('electrical', 'Electrical'), ('distributed_energy', 'Distributed Energy'), ('telecommunications', 'Telecommunications'), ('resource', 'Resource'), ('other', 'Other'), ('contractor_shop', 'Contractor/Shop'), ('operations', 'Operations')], max_length=32), blank=True, default=list, help_text='List of disciplines this note relates to (can be multiple)', size=None),
        ),
    ]
