# Generated by Django 5.1 on 2026-02-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0078_add_discipline_fields_to_drawing_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingpage',
            name='sheet_discipline',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('hazardous_materials', 'Hazardous Materials'), ('survey_mapping', 'Survey/Mapping'), ('geotechnical', 'Geotechnical'), ('civil', 'Civil'), ('landscape', 'Landscape'), ('structural', 'Structural'), ('architectural', 'Architectural'), ('interiors', 'Interiors'), ('equipment', 'Equipment'), ('fire_protection', 'Fire Protection'), ('plumbing', 'Plumbing'), ('process', 'Process'), ('mechanical', 'Mechanical'), ('electrical', 'Electrical'), ('distributed_energy', 'Distributed Energy'), ('telecommunications', 'Telecommunications'), ('resource', 'Resource'), ('other', 'Other'), ('contractor_shop', 'Contractor/Shop'), ('operations', 'Operations')], db_index=True, help_text='Primary discipline of the sheet based on sheet number prefix (e.g., M-101 → mechanical)', max_length=32, null=True),
        ),
    ]
