# Generated by Django 5.1 on 2026-02-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0077_add_spec_comparison_models'),
        ('deliverables', '0079_add_sheet_discipline_index'),
    ]

    operations = [
    ]
