# Generated by Django 5.1 on 2026-02-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0078_normalize_paragraph_number_nulls'),
        ('deliverables', '0080_merge_20260203_2307'),
    ]

    operations = [
    ]
