# Generated by Django 5.1 on 2026-02-21 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0081_merge_20260221_1625'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specconflict',
            name='status',
            field=models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('RFI', 'RFI'), ('ACCEPT', 'Accept'), ('NEEDS_REVIEW', 'Needs Review'), ('REVISION_INCOMING', 'Revision Incoming')], db_index=True, default='UNREVIEWED', max_length=32),
        ),
        migrations.CreateModel(
            name='SpecConflictComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='deliverables.specconflict')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_conflict_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conflict', 'created_at'], name='deliverable_conflic_99be2f_idx')],
            },
        ),
    ]
