# Generated by Django 5.1 on 2026-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0082_specconflict_status_specconflictcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specconflictcomment',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterField(
            model_name='specconflictcomment',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
