# Generated by Django 5.1 on 2024-10-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_customer_customuser_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
