# Generated by Django 5.1 on 2024-10-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='legacy_role_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
