# Generated by Django 5.1 on 2025-01-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_legacy_role_id'),
    ]

    operations = [
    ]
