# Generated by Django 5.1 on 2024-09-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0001_initial'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='team',
            name='enterprise_billing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='entitlements',
            field=models.ManyToManyField(blank=True, to='deliverables.entitlement'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_enterprise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='member_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='project_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
