# Generated by Django 5.1 on 2024-10-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_options_team_enterprise_billing_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='legacy_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='legacy_admin_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='legacy_customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='legacy_logo_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='legacy_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='procore_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='procore_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
