# Generated by Django 5.1 on 2024-11-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_teamprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamProfile',
        ),
    ]
