# Generated by Django 5.1 on 2025-02-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0040_projectversion_unique_project_version_name'),
        ('teams', '0007_delete_teamprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Activate this flag for these projects.', to='deliverables.project'),
        ),
    ]
