# Generated by Django 5.1 on 2025-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_flag_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sso_domain',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
