/* tslint:disable */
/* eslint-disable */
/**
 * The Link
 * Web application for The Link.ai
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Role9aaEnum } from './Role9aaEnum';
import {
    Role9aaEnumFromJSON,
    Role9aaEnumFromJSONTyped,
    Role9aaEnumToJSON,
} from './Role9aaEnum';

/**
 * 
 * @export
 * @interface Membership
 */
export interface Membership {
    /**
     * 
     * @type {number}
     * @memberof Membership
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof Membership
     */
    readonly userId: number;
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    readonly firstName: string;
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    readonly lastName: string;
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    readonly displayName: string;
    /**
     * 
     * @type {Role9aaEnum}
     * @memberof Membership
     */
    role: Role9aaEnum;
}

/**
 * Check if a given object implements the Membership interface.
 */
export function instanceOfMembership(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('userId' in value)) return false;
    if (!('firstName' in value)) return false;
    if (!('lastName' in value)) return false;
    if (!('displayName' in value)) return false;
    if (!('role' in value)) return false;
    return true;
}

export function MembershipFromJSON(json: any): Membership {
    return MembershipFromJSONTyped(json, false);
}

export function MembershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): Membership {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'displayName': json['display_name'],
        'role': Role9aaEnumFromJSON(json['role']),
    };
}

export function MembershipToJSON(value?: Omit<Membership, 'id'|'user_id'|'first_name'|'last_name'|'display_name'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'role': Role9aaEnumToJSON(value['role']),
    };
}

