/* tslint:disable */
/* eslint-disable */
/**
 * The Link
 * Web application for The Link.ai
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Project } from './Project';
import {
    ProjectFromJSON,
    ProjectFromJSONTyped,
    ProjectToJSON,
} from './Project';

/**
 * 
 * @export
 * @interface PaginatedProjectList
 */
export interface PaginatedProjectList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedProjectList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProjectList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProjectList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Project>}
     * @memberof PaginatedProjectList
     */
    results: Array<Project>;
}

/**
 * Check if a given object implements the PaginatedProjectList interface.
 */
export function instanceOfPaginatedProjectList(value: object): boolean {
    if (!('count' in value)) return false;
    if (!('results' in value)) return false;
    return true;
}

export function PaginatedProjectListFromJSON(json: any): PaginatedProjectList {
    return PaginatedProjectListFromJSONTyped(json, false);
}

export function PaginatedProjectListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedProjectList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ProjectFromJSON)),
    };
}

export function PaginatedProjectListToJSON(value?: PaginatedProjectList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ProjectToJSON)),
    };
}

