/* tslint:disable */
/* eslint-disable */
/**
 * The Link
 * Web application for The Link.ai
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectMembership } from './ProjectMembership';
import {
    ProjectMembershipFromJSON,
    ProjectMembershipFromJSONTyped,
    ProjectMembershipToJSON,
} from './ProjectMembership';

/**
 * 
 * @export
 * @interface PatchedProject
 */
export interface PatchedProject {
    /**
     * 
     * @type {number}
     * @memberof PatchedProject
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedProject
     */
    team?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedProject
     */
    owner?: number;
    /**
     * 
     * @type {Array<ProjectMembership>}
     * @memberof PatchedProject
     */
    members?: Array<ProjectMembership>;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    readonly entitlements?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedProject
     */
    userLimit?: number;
}

/**
 * Check if a given object implements the PatchedProject interface.
 */
export function instanceOfPatchedProject(value: object): boolean {
    return true;
}

export function PatchedProjectFromJSON(json: any): PatchedProject {
    return PatchedProjectFromJSONTyped(json, false);
}

export function PatchedProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'team': json['team'] == null ? undefined : json['team'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(ProjectMembershipFromJSON)),
        'entitlements': json['entitlements'] == null ? undefined : json['entitlements'],
        'userLimit': json['user_limit'] == null ? undefined : json['user_limit'],
    };
}

export function PatchedProjectToJSON(value?: Omit<PatchedProject, 'id'|'entitlements'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'team': value['team'],
        'owner': value['owner'],
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(ProjectMembershipToJSON)),
        'user_limit': value['userLimit'],
    };
}

