/* tslint:disable */
/* eslint-disable */
/**
 * The Link
 * Web application for The Link.ai
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `project_admin` - Project Administrator
 * * `project_member` - Project Member
 * * `project_external_user` - Project External User
 * @export
 */
export const ProjectMembershipRoleEnum = {
    Admin: 'project_admin',
    Member: 'project_member',
    ExternalUser: 'project_external_user'
} as const;
export type ProjectMembershipRoleEnum = typeof ProjectMembershipRoleEnum[keyof typeof ProjectMembershipRoleEnum];


export function instanceOfProjectMembershipRoleEnum(value: any): boolean {
    return Object.values(ProjectMembershipRoleEnum).includes(value);
}

export function ProjectMembershipRoleEnumFromJSON(json: any): ProjectMembershipRoleEnum {
    return ProjectMembershipRoleEnumFromJSONTyped(json, false);
}

export function ProjectMembershipRoleEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectMembershipRoleEnum {
    return json as ProjectMembershipRoleEnum;
}

export function ProjectMembershipRoleEnumToJSON(value?: ProjectMembershipRoleEnum | null): any {
    return value as any;
}

