/* tslint:disable */
/* eslint-disable */
/**
 * The Link
 * Web application for The Link.ai
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectMembershipRoleEnum } from './ProjectMembershipRoleEnum';
import {
    ProjectMembershipRoleEnumFromJSON,
    ProjectMembershipRoleEnumFromJSONTyped,
    ProjectMembershipRoleEnumToJSON,
} from './ProjectMembershipRoleEnum';

/**
 * 
 * @export
 * @interface ProjectMembership
 */
export interface ProjectMembership {
    /**
     * 
     * @type {number}
     * @memberof ProjectMembership
     */
    readonly userId: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectMembership
     */
    readonly firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectMembership
     */
    readonly lastName: string;
    /**
     * 
     * @type {ProjectMembershipRoleEnum}
     * @memberof ProjectMembership
     */
    role: ProjectMembershipRoleEnum;
}

/**
 * Check if a given object implements the ProjectMembership interface.
 */
export function instanceOfProjectMembership(value: object): boolean {
    if (!('userId' in value)) return false;
    if (!('firstName' in value)) return false;
    if (!('lastName' in value)) return false;
    if (!('role' in value)) return false;
    return true;
}

export function ProjectMembershipFromJSON(json: any): ProjectMembership {
    return ProjectMembershipFromJSONTyped(json, false);
}

export function ProjectMembershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectMembership {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'role': ProjectMembershipRoleEnumFromJSON(json['role']),
    };
}

export function ProjectMembershipToJSON(value?: Omit<ProjectMembership, 'user_id'|'first_name'|'last_name'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'role': ProjectMembershipRoleEnumToJSON(value['role']),
    };
}

