/* tslint:disable */
/* eslint-disable */
/**
 * The Link
 * Web application for The Link.ai
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectMembership } from './ProjectMembership';
import {
    ProjectMembershipFromJSON,
    ProjectMembershipFromJSONTyped,
    ProjectMembershipToJSON,
} from './ProjectMembership';

/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    team: number;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    owner: number;
    /**
     * 
     * @type {Array<ProjectMembership>}
     * @memberof Project
     */
    members: Array<ProjectMembership>;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    readonly entitlements: string;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    userLimit?: number;
}

/**
 * Check if a given object implements the Project interface.
 */
export function instanceOfProject(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('team' in value)) return false;
    if (!('owner' in value)) return false;
    if (!('members' in value)) return false;
    if (!('entitlements' in value)) return false;
    return true;
}

export function ProjectFromJSON(json: any): Project {
    return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'team': json['team'],
        'owner': json['owner'],
        'members': ((json['members'] as Array<any>).map(ProjectMembershipFromJSON)),
        'entitlements': json['entitlements'],
        'userLimit': json['user_limit'] == null ? undefined : json['user_limit'],
    };
}

export function ProjectToJSON(value?: Omit<Project, 'id'|'entitlements'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'team': value['team'],
        'owner': value['owner'],
        'members': ((value['members'] as Array<any>).map(ProjectMembershipToJSON)),
        'user_limit': value['userLimit'],
    };
}

