/* tslint:disable */
/* eslint-disable */
/**
 * The Link
 * Web application for The Link.ai
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `admin` - Administrator
 * * `member` - Member
 * @export
 */
export const Role9aaEnum = {
    Admin: 'admin',
    Member: 'member'
} as const;
export type Role9aaEnum = typeof Role9aaEnum[keyof typeof Role9aaEnum];


export function instanceOfRole9aaEnum(value: any): boolean {
    return Object.values(Role9aaEnum).includes(value);
}

export function Role9aaEnumFromJSON(json: any): Role9aaEnum {
    return Role9aaEnumFromJSONTyped(json, false);
}

export function Role9aaEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): Role9aaEnum {
    return json as Role9aaEnum;
}

export function Role9aaEnumToJSON(value?: Role9aaEnum | null): any {
    return value as any;
}

