name: Deploy to QA

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: deliverables-dev
  ECS_SERVICE: deliverables-dev-api-django           # name of the service
  ECS_CLUSTER: deliverables-dev                     # name of the cluster
  ECS_TASK_DEFINITION: .aws/task-definition.json     # path of the JSON task definition
  CONTAINER_NAME: "deliverables-dev-api-django"           # name of the container name in the task definition
  ENVIRONMENT: qa

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            --build-arg ENVIRONMENT="${{ env.ENVIRONMENT }}" \
            --build-arg SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --build-arg AWS_ACCESS_KEY_ID="${{ vars.AWS_ACCESS_KEY_ID }}" \
            --build-arg AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --build-arg SIMPLE_JWT_SIGNING_KEY="${{ secrets.SIMPLE_JWT_SIGNING_KEY }}" \
            --build-arg CORS_ALLOWED_ORIGINS="${{ vars.CORS_ALLOWED_ORIGINS }}" \
            --build-arg LEGACY_DB_PASSWORD="${{ secrets.LEGACY_DB_PASSWORD }}" \
            --build-arg LEGACY_DB_HOST="${{ vars.LEGACY_DB_HOST }}" \
            --build-arg AWS_REGION="${{ vars.AWS_REGION }}" \
            --build-arg S3_BUCKET="${{ vars.S3_BUCKET }}" \
            --build-arg LAMBDA_FUNCTION_URL="${{ vars.LAMBDA_FUNCTION_URL }}" \
            --build-arg BACKEND_CALLBACK_URL="${{ vars.BACKEND_CALLBACK_URL }}" \
            --build-arg FRONTEND_BASE_URL="${{ vars.FRONTEND_BASE_URL }}" \
            --build-arg SENDGRID_API_KEY="${{ secrets.SENDGRID_API_KEY }}" \
            --build-arg NOTICES_LAMBDA_FUNCTION_URL="${{ vars.NOTICES_LAMBDA_FUNCTION_URL }}" \
            --build-arg BACKEND_NOTICES_CALLBACK_URL="${{ vars.BACKEND_NOTICES_CALLBACK_URL }}" \
            --build-arg V2_PROCESS_DELIVERABLES_LAMBDA_FUNCTION_URL="${{ vars.V2_PROCESS_DELIVERABLES_LAMBDA_FUNCTION_URL }}" \
            --build-arg BACKEND_FULL_SPEC_PROCESSING_CALLBACK_URL="${{ vars.BACKEND_FULL_SPEC_PROCESSING_CALLBACK_URL }}" \
            --build-arg PROCORE_CLIENT_ID="${{ vars.PROCORE_CLIENT_ID }}" \
            --build-arg PROCORE_CLIENT_SECRET="${{ secrets.PROCORE_CLIENT_SECRET }}" \
            --build-arg PROCORE_REDIRECT_URL="${{ vars.PROCORE_REDIRECT_URL }}" \
            --build-arg PROCORE_AUTH_BASE_URL="${{ vars.PROCORE_AUTH_BASE_URL }}" \
            --build-arg PROCORE_BASE_URL="${{ vars.PROCORE_BASE_URL }}" \
            --build-arg ELLIS_DON_SSO_CLIENT_ID="${{ vars.ELLIS_DON_SSO_CLIENT_ID }}" \
            --build-arg ELLIS_DON_SSO_CLIENT_SECRET="${{ secrets.ELLIS_DON_SSO_CLIENT_SECRET }}" \
            --build-arg ELLIS_DON_SSO_TENANT_ID="${{ vars.ELLIS_DON_SSO_TENANT_ID }}" \
            --build-arg THE_LINK_SSO_CLIENT_ID="${{ vars.THE_LINK_SSO_CLIENT_ID }}" \
            --build-arg THE_LINK_SSO_CLIENT_SECRET="${{ secrets.THE_LINK_SSO_CLIENT_SECRET }}" \
            --build-arg THE_LINK_SSO_TENANT_ID="${{ vars.THE_LINK_SSO_TENANT_ID }}" \
            --build-arg PINECONE_INDEX_NAME="${{ vars.PINECONE_INDEX_NAME }}" \
            --build-arg BACKEND_SPECGPT_CALLBACK_URL="${{ vars.BACKEND_SPECGPT_CALLBACK_URL }}" \
            --build-arg PROMPTLAYER_API_KEY="${{ secrets.PROMPTLAYER_API_KEY }}" \
            --build-arg PINECONE_API_KEY="${{ secrets.PINECONE_API_KEY }}" \
            --build-arg OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            --build-arg BACKEND_BASE_URL="${{ vars.BACKEND_BASE_URL }}" \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ./Dockerfile.deploy .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true